
[config]
schemaVersion = "0.0.1"

[package]
namespace = "tristanmcpherson"
name = "R2API"
versionNumber = "5.0.1"
description = "A modding API for Risk of Rain 2"
websiteUrl = "https://github.com/risk-of-thunder/R2API"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.2103"
RiskofThunder-HookGenPatcher = "1.2.3"
RiskofThunder-R2API_ArtifactCode = "1.0.0"
RiskofThunder-R2API_CommandHelper = "1.0.0"
RiskofThunder-R2API_ContentManagement = "1.0.0"
RiskofThunder-R2API_Core = "1.0.0"
RiskofThunder-R2API_DamageType = "1.0.0"
RiskofThunder-R2API_Deployable = "1.0.0"
RiskofThunder-R2API_Difficulty = "1.0.0"
RiskofThunder-R2API_Director = "1.0.0"
RiskofThunder-R2API_Dot = "1.0.0"
RiskofThunder-R2API_Elites = "1.0.0"
RiskofThunder-R2API_Items = "1.0.0"
RiskofThunder-R2API_Language = "1.0.0"
RiskofThunder-R2API_Loadout = "1.0.0"
RiskofThunder-R2API_LobbyConfig = "1.0.0"
RiskofThunder-R2API_Networking = "1.0.0"
RiskofThunder-R2API_Orb = "1.0.0"
RiskofThunder-R2API_Prefab = "1.0.0"
RiskofThunder-R2API_RecalculateStats = "1.0.0"
RiskofThunder-R2API_SceneAsset = "1.0.0"
RiskofThunder-R2API_Sound = "1.0.0"
RiskofThunder-R2API_TempVisualEffect = "1.0.0"
RiskofThunder-R2API_Unlockable = "1.0.0"

[build]
icon = "../icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput"
target = "./plugins/R2API.Legacy"

[publish]
repository = "https://thunderstore.io"
communities = ["riskofrain2"]
categories = ["libraries"]
