
[config]
schemaVersion = "0.0.1"

[package]
namespace = "RiskofThunder"
name = "R2API_Teams"
versionNumber = "1.0.1"
description = "API for registering and handling custom teams"
websiteUrl = "https://github.com/risk-of-thunder/R2API"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.2109"
RiskofThunder-HookGenPatcher = "1.2.3"
RiskofThunder-R2API_Core = "5.1.7"

[build]
icon = "../icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput/R2API.Teams.dll"
target = "./plugins/R2API.Teams/R2API.Teams.dll"

[[build.copy]]
source = "./ReleaseOutput/R2API.Teams.xml"
target = "./plugins/R2API.Teams/R2API.Teams.xml"

[[build.copy]]
source = "../R2API.Teams.Interop/ReleaseOutput/R2API.Teams.Interop.dll"
target = "./plugins/R2API.Teams/R2API.Teams.Interop.dll"

[[build.copy]]
source = "../R2API.Teams.Patcher/ReleaseOutput/R2API.Teams.Patcher.dll"
target = "./patchers/R2API.Teams/R2API.Teams.Patcher.dll"

[publish]
repository = "https://thunderstore.io"
communities = ["riskofrain2"]
categories = ["libraries"]
