
[config]
schemaVersion = "0.0.1"

[package]
namespace = "RiskofThunder"
name = "R2API_Execute"
versionNumber = "1.1.2"
description = "API for manipulating Execute Threshold"
websiteUrl = "https://github.com/risk-of-thunder/R2API"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.2121"
RiskofThunder-HookGenPatcher = "1.2.9"
RiskofThunder-R2API_Core = "1.0.0"

[build]
icon = "../icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput"
target = "./plugins/R2API.Execute"

[publish]
repository = "https://thunderstore.io"
communities = ["riskofrain2"]
categories = ["libraries"]
